# Generated by Django 5.1.4 on 2024-12-11 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_owner', models.ImageField(upload_to='images_owner/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_pet', models.ImageField(upload_to='images_pet/')),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_by_id_owner', to='qr_pet_tracker.owner')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_by_owner', to='qr_pet_tracker.owner')),
            ],
        ),
    ]
